export enum PropertyType {
  APARTMENT = "apartment",
  DUPLEX_HOUSE = "duplex_house",
  COMMERCIAL = "commercial",
  LUXARY_VILAS = "luxary_vilas",
  PICTURE_STUDIO = "picture_studio",
  OFFICE = "office",
  WAREHOUSE = "warehouse",
  INDUSTRIAL = "industrial",
  RETAIL = "retail",
  HOTEL = "hotel",
  RESORT = "resort",
  FARM = "farm",
  VILLA = "villa",
  OTHER = "other",
}

export enum PropertyFlag {
  SELL = "sell",
  RENT = "rent",
  LEASE = "lease",
}

export enum RateOption {
  DAY = "day",
  WEEK = "week",
  MONTH = "month",
  YEAR = "yearly",
  BUY = "buy",
}

export enum ProperTyStatus {
  AVAILABLE = "available",
  IN_DEAL = "in_deal",
  RENTED = "rented",
  ARCHIVED = "archived",
}

export enum Currency {
  USD = "USD",
  EUR = "EUR",
  GBP = "GBP",
  CAD = "CAD",
  AUD = "AUD",
  NZD = "NZD",
  JPY = "JPY",
  CNY = "CNY",
  INR = "INR",
  PKR = "PKR",
  AED = "AED",
  SAR = "SAR",
  QAR = "QAR",
  KWD = "KWD",
  BHD = "BHD",
  OMR = "OMR",
  BDT = "BDT",
  LKR = "LKR",
  NPR = "NPR",
  MVR = "MVR",
  MYR = "MYR",
  SGD = "SGD",
  THB = "THB",
  IDR = "IDR",
  PHP = "PHP",
  VND = "VND",
  KRW = "KRW",
  ZAR = "ZAR",
  NGN = "NGN",
  GHS = "GHS",
  KES = "KES",
  TZS = "TZS",
  UGX = "UGX",
  RWF = "RWF",
  MWK = "MWK",
  ZMW = "ZMW",
  MZN = "MZN",
  XAF = "XAF",
  XOF = "XOF",
  XCD = "XCD",
  BSD = "BSD",
  BBD = "BBD",
  BZD = "BZD",
  KYD = "KYD",
  JMD = "JMD",
  TTD = "TTD",
  XPF = "XPF",
  TOP = "TOP",
  WST = "WST",
  SBD = "SBD",
  PGK = "PGK",
  FJD = "FJD",
  LRD = "LRD",
  SRD = "SRD",
  GYD = "GYD",
  HTG = "HTG",
  ANG = "ANG",
  AWG = "AWG",
  NIO = "NIO",
  CRC = "CRC",
  SVC = "SVC",
  BMD = "BMD",
  BND = "BND",
  BWP = "BWP",
  BIF = "BIF",
  DJF = "DJF",
  ERN = "ERN",
  ETB = "ETB",
  GNF = "GNF",
  KMF = "KMF",
}
